[package]
name = "spikard-http"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "HTTP server for spikard"

[dependencies]
spikard.workspace = true
axum = { workspace = true, features = ["multipart"] }
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
jsonschema = "0.33"
serde_qs = "0.15"
lazy_static = "1.5"
regex = "1"
rustc-hash = "2.1"
urlencoding = "2.1"
mime = "0.3"
jiff = "0.1"
pyo3.workspace = true
pyo3-async-runtimes.workspace = true
bytes = "1.10"
http-body-util = "0.1"
axum-test = "18"
anyhow = "1.0"
cookie = "0.18"

[dev-dependencies]
