spin_manifest_version = 2

[application]
name = "spin-bench"
version = "0.1.0"
description = "Spin benchmark app"

[[trigger.http]]
route = "/..."
component = "spin-bench"

[component.spin-bench]
source = "target/wasm32-wasip2/release/spin_bench.wasm"
[component.spin-bench.build]
command = "cargo build --target wasm32-wasip2 --release"
