[package]
name = "spikard-py"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Python bindings (PyO3) for spikard"

[lib]
name = "_spikard"
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
spikard.workspace = true
spikard-http = { path = "../spikard-http" }
pyo3.workspace = true
pyo3-async-runtimes.workspace = true
pythonize = "0.27"
serde_json.workspace = true
axum.workspace = true
axum-test = "18"
bytes = "1.11"
http-body-util = "0.1"
urlencoding = "2.1"
once_cell = "1.21"
tokio.workspace = true
tracing.workspace = true
async-stream = "0.3"

[dev-dependencies]

[features]
default = []
extension-module = ["pyo3/extension-module"]
