name = "spikard-wasm-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-12-02"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "spikard-wasm-cloudflare-dev"

[env.production]
name = "spikard-wasm-cloudflare-prod"
