[project]
name = "robyn-benchmark"
version = "0.1.0"
description = "Robyn benchmark application"
requires-python = ">=3.11,<3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "pydantic>=2.12.5",
  "robyn>=0.72.2",
]
