[package]
name = "spikard-rb-ext"
version = "0.10.1"
edition = "2024"
license = "MIT"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]

[lib]
name = "spikard_rb"
crate-type = ["cdylib"]

[workspace]

[dependencies]
magnus = { version = "0.8.2", features = ["rb-sys"] }
# Use crates from the workspace root
spikard_rb_core = { package = "spikard-rb", path = "../../../../crates/spikard-rb" }
