[package]
name = "spikard-rb-ext"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]

[lib]
name = "spikard_rb"
crate-type = ["cdylib"]

[workspace]

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus", rev = "f6db11769efb517427bf7f121f9c32e18b059b38", features = ["rb-sys"] }
spikard-rb = { path = "../../../../crates/spikard-rb" }
