[package]
name = "spikard-rb-ext"
version = "0.2.0"
edition = "2024"
license = "MIT"
authors = ["Na'aman Hirschfeld <nhirschfeld@gmail.com>"]

[lib]
name = "spikard_rb"
crate-type = ["cdylib"]

[workspace]

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus", rev = "f6db11769efb517427bf7f121f9c32e18b059b38", features = ["rb-sys"] }
# Vendored workspace crates - created by rake vendor:sync before gem build
spikard_rb_core = { package = "spikard-rb", path = "../../vendor/spikard-rb" }
